@startuml retiros

class Retiro{
    nombre
    costoTotal
    fechaInicio
    fechaFin
    ubicacion
    descripcion
    cancelable:bool
    pago:Pago
    tematica:Tematica
    estado:Estado
    cronograma:Cronograma
    organizador:Organizador
    alertas:Alerta
    valoraciones:Valoracion

    crear()
    mostrar()
    conocerPago()
    conocerTematica()
    conocerCronograma()
    conocerOrganizador()
    conocerAlerta()
    conocerEstado()
    conocerValoracion()
    agregarValoracion()
    compartir()
}

class Valoracion{
    puntuacion
    comentario
    multimedia
    volveriaAIr:bool

    crear()
    mostrar()
    cargarMultimedia()
}

class Estado{
    nombre
    descripcion

    crear()
    mostrar()
    tomarNombre()
    tomarDescripcion()
    mostrarNombre()
    mostrarDescripcion()
}

class Organizador{
    nombre
    correoElectronico
    telefono

    crear()
    mostrar()
}


note bottom of Estado : Los metodos de seteo aplicados en esta \n clase se extienden para todo el diagrama

@enduml